apiVersion: apps/v1
kind: Deployment
metadata:
  name: ljoolgld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ljoolgld
  template:
    metadata:
      labels:
        app: ljoolgld
    spec:
      containers:
      - image: okteto.dev/ljoolgld:latest
        name: ljoolgld
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0b4d0472-4024-4c34-8da6-8d52faba09d8"
        - name: Vless_Path
          value: "/vl55ngjdfhd5"
        - name: Vmess_UUID
          value: "0b4d0472-4024-4c34-8da6-8d52faba09d8"
        - name: Vmess_Path
          value: "/vm6gfdhd6"
        - name: Share_Path
          value: "/v2link"
